import { expect, test } from '@playwright/test'

const menus = [
  { code: 'STATS', groupCode: 'MANAGE', groupName: '管理', name: '数据统计', path: '/index', sort: 10, enabled: true },
  { code: 'CLUES', groupCode: 'BUSINESS', groupName: '业务', name: '客户列表', path: '/clues', sort: 20, enabled: true },
  { code: 'ASSIGN', groupCode: 'BUSINESS', groupName: '业务', name: '分配管理', path: '/assign', sort: 40, enabled: true },
  { code: 'DEALS', groupCode: 'BUSINESS', groupName: '业务', name: '成交记录', path: '/deals', sort: 50, enabled: true },
  { code: 'THIRD_PARTY_POOL', groupCode: 'BUSINESS', groupName: '业务', name: '三方下载池', path: '/third-party-pool', sort: 60, enabled: true }
]

test.skip(({ isMobile }) => isMobile, '业务流程 E2E 使用桌面表格布局验证，移动端体验由独立用例覆盖')

test('销售可以领取线索并释放回公共池', async ({ page }) => {
  await loginAs(page, {
    name: '销售A',
    employeeCode: 'SA',
    role: 'EMPLOYEE',
    position: 'SALES',
    menuPermissions: ['STATS', 'ASSIGN']
  })

  let poolMode = 'public'
  let claimCalled = false
  let releaseCalled = false
  await mockCommonApis(page)
  await page.route('**/api/auth/sales', (route) => fulfillApi(route, success([
    { name: '销售A', employeeCode: 'SA', position: 'SALES' }
  ])))
  await page.route('**/api/clues/sales-pool/public**', (route) => fulfillApi(route, success(pageData(poolMode === 'public' ? [publicClue()] : []))))
  await page.route('**/api/clues/sales-pool/mine**', (route) => fulfillApi(route, success(pageData(poolMode === 'mine' ? [mineClue()] : []))))
  await page.route('**/api/clues/XA0705-01/claim', (route) => {
    claimCalled = true
    poolMode = 'mine'
    return fulfillApi(route, success(mineClue()))
  })
  await page.route('**/api/clues/XA0705-01/release', (route) => {
    releaseCalled = true
    poolMode = 'public'
    return fulfillApi(route, success(publicClue()))
  })

  await page.goto('/assign')
  await expect(page.getByText('公共待分配池')).toBeVisible()
  await page.getByRole('button', { name: '领取' }).click()
  await page.locator('.el-message-box').getByRole('button', { name: '确认领取' }).click({ force: true })
  await expect.poll(() => claimCalled).toBe(true)

  await page.getByRole('button', { name: '我的销售池' }).click()
  await expect(page.locator('.el-loading-mask')).toHaveCount(0)
  await expect(page.locator('.desktop-table').getByRole('button', { name: '释放' })).toBeVisible()
  await page.locator('.desktop-table').getByRole('button', { name: '释放' }).click()
  await page.locator('.el-message-box textarea').fill('客户暂不跟进')
  await page.locator('.el-message-box').getByRole('button', { name: '确认释放回公共池' }).click({ force: true })
  await expect.poll(() => releaseCalled).toBe(true)
})

test('成交记录可以执行退单流程', async ({ page }) => {
  await loginAs(page, {
    name: '销售A',
    employeeCode: 'SA',
    role: 'EMPLOYEE',
    position: 'SALES',
    menuPermissions: ['STATS', 'DEALS']
  })

  let cancelled = false
  await mockCommonApis(page)
  await page.route('**/api/auth/sales', (route) => fulfillApi(route, success([
    { name: '销售A', employeeCode: 'SA', position: 'SALES' }
  ])))
  await page.route('**/api/deals**', (route) => fulfillApi(route, success(pageData([
    {
      dealCode: 'D0705001',
      customerCode: 'XA0705-01',
      customerName: '测试客户',
      status: cancelled ? 'REFUNDED' : 'DEPOSIT_PAID',
      deposit: '500',
      remainingBalance: '1500',
      refundAmount: cancelled ? '500' : '',
      dealUser: '销售A',
      dealUserCode: 'SA',
      dealDate: '2026-07-05',
      itinerary: '北京三日游',
      autoGenerated: false
    }
  ]))))
  await page.route('**/api/deals/D0705001/cancel', (route) => {
    cancelled = true
    return fulfillApi(route, success({ dealCode: 'D0705001', status: 'REFUNDED' }))
  })

  await page.goto('/deals')
  await expect(page.getByText('D0705001')).toBeVisible()
  await page.getByRole('button', { name: '退单' }).click()
  await page.getByRole('button', { name: '继续退单' }).click()
  await page.getByLabel('退单金额').fill('500')
  await page.getByRole('button', { name: '确认退单' }).click()
  await expect.poll(() => cancelled).toBe(true)
  await expect(page.getByText('退单').first()).toBeVisible()
})

test('三方下载池下载 Word 后会标记为已下载', async ({ page }) => {
  await loginAs(page, {
    name: 'admin',
    employeeCode: 'ADMIN',
    role: 'ADMIN',
    position: 'OPERATION',
    menuPermissions: ['STATS', 'THIRD_PARTY_POOL']
  })

  let downloaded = false
  await mockCommonApis(page)
  await page.route('**/api/third-party-downloads/pending**', (route) => fulfillApi(route, success(pageData(downloaded ? [] : [thirdPartyRow()]))))
  await page.route('**/api/third-party-downloads/downloaded**', (route) => fulfillApi(route, success(pageData(downloaded ? [{ ...thirdPartyRow(), downloadedAt: '2026-07-05 10:30', downloadedBy: 'admin', downloadedByCode: 'ADMIN' }] : []))))
  await page.route('**/api/third-party-downloads/failures**', (route) => fulfillApi(route, success(pageData([]))))
  await page.route('**/api/clues/XA0705-01/word', (route) => route.fulfill({
    contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    headers: { 'Content-Disposition': "attachment; filename*=UTF-8''XA0705-01.docx" },
    body: Buffer.from([1, 2, 3])
  }))
  await page.route('**/api/third-party-downloads/XA0705-01/mark-downloaded', (route) => {
    downloaded = true
    return fulfillApi(route, success(true))
  })

  await page.goto('/third-party-pool')
  await expect(page.locator('.desktop-table').getByText('XA0705-01')).toBeVisible()
  const download = page.waitForEvent('download')
  await page.locator('.desktop-table').getByRole('button', { name: '下载' }).click()
  await download
  await expect.poll(() => downloaded).toBe(true)
})

async function loginAs(page, user) {
  await page.addInitScript((storedUser) => {
    window.__CRM_DISABLE_REALTIME__ = true
    localStorage.setItem('crm_user', JSON.stringify(storedUser))
    localStorage.setItem('crm_session_expires_at', String(Date.now() + 24 * 60 * 60 * 1000))
  }, user)
}

async function mockCommonApis(page) {
  await page.route('**/api/menus', (route) => fulfillApi(route, success(menus)))
  await page.route('**/ws/**', (route) => route.abort())
}

function success(data) {
  return { success: true, data }
}

function fulfillApi(route, body) {
  return route.fulfill({
    contentType: 'application/json',
    body: JSON.stringify(body)
  })
}

function pageData(records) {
  return { records, total: records.length, page: 1, pageSize: 10, hasMore: false }
}

function publicClue() {
  return {
    customerCode: 'XA0705-01',
    sourcePlatform: 'DOUYIN',
    addMethod: 'ACTIVE',
    contactInfo: 'wx123',
    uploader: '小白',
    uploaderEmployeeCode: 'XA',
    assignedSales: '',
    assignedSalesEmployeeCode: '',
    status: 'NEW',
    createdAt: '2026-07-05 10:00',
    assignLogs: []
  }
}

function mineClue() {
  return {
    ...publicClue(),
    status: 'FOLLOWING',
    assignedSales: '销售A',
    assignedSalesEmployeeCode: 'SA'
  }
}

function thirdPartyRow() {
  return {
    ...publicClue(),
    douyinImages: [],
    wechatImages: []
  }
}
